/**
 * Cloudflare Worker entry point -- auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 */
import { fetchWorkerFilesystemRoute, runPagesRequest, wrapMiddlewareWithBasePath } from "vinext/server/pages-request-pipeline";
import type { PagesPipelineDeps } from "vinext/server/pages-request-pipeline";
import { handleImageOptimization, DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES, isImageOptimizationPath } from "vinext/server/image-optimization";
import type { ImageConfig } from "vinext/server/image-optimization";
import { cloneRequestWithHeaders, cloneRequestWithUrl, filterInternalHeaders, isOpenRedirectShaped } from "vinext/server/request-pipeline";
import { notFoundStaticAssetResponse } from "vinext/server/http-error-responses";
import { finalizeMissingStaticAssetResponse } from "vinext/server/worker-utils";
import { assetPrefixPathname, isNextStaticPath } from "vinext/utils/asset-prefix";
import { hasBasePath, stripBasePath } from "vinext/utils/base-path";

// @ts-expect-error -- virtual module resolved by vinext at build time
import { renderPage, handleApiRoute, runMiddleware, normalizeDataRequest, vinextConfig, matchPageRoute } from "virtual:vinext-server-entry";
// @ts-expect-error -- virtual module resolved by vinext at build time
import { registerConfiguredCacheAdapters } from "virtual:vinext-cache-adapters";

interface Env {
  ASSETS: Fetcher;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

// Extract config values (embedded at build time in the server entry)
const basePath: string = vinextConfig?.basePath ?? "";
const assetPathPrefix: string = assetPrefixPathname(vinextConfig?.assetPrefix ?? "");
const trailingSlash: boolean = vinextConfig?.trailingSlash ?? false;
const i18nConfig = vinextConfig?.i18n ?? null;
const configRedirects = vinextConfig?.redirects ?? [];
const configRewrites = vinextConfig?.rewrites ?? { beforeFiles: [], afterFiles: [], fallback: [] };
const configHeaders = vinextConfig?.headers ?? [];
const imageConfig: ImageConfig | undefined = vinextConfig?.images ? {
  qualities: vinextConfig.images.qualities,
  dangerouslyAllowSVG: vinextConfig.images.dangerouslyAllowSVG,
  dangerouslyAllowLocalIP: vinextConfig.images.dangerouslyAllowLocalIP,
  contentDispositionType: vinextConfig.images.contentDispositionType,
  contentSecurityPolicy: vinextConfig.images.contentSecurityPolicy,
} : undefined;

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    // Pass the Worker `env` so binding-backed adapters (e.g. KV) resolve.
    registerConfiguredCacheAdapters(env);
    try {
      const url = new URL(request.url);
      let pathname = url.pathname;

      // Block protocol-relative URL open redirects in all shapes:
      //   literal  //evil.com, /\\evil.com
      //   encoded  /%5Cevil.com, /%2F/evil.com
      // Browsers normalize backslash to forward slash, and they percent-decode
      // Location headers, so an encoded backslash in a downstream 308 redirect
      // would also navigate to the attacker's origin.
      if (isOpenRedirectShaped(pathname)) {
        return new Response("This page could not be found", { status: 404 });
      }

      // Valid assets are served by Cloudflare's ASSETS binding before the
      // worker runs. Missing asset-shaped requests still need to reach
      // middleware so it can rewrite or respond; a final 404 is converted
      // back to Next.js's canonical plain-text static-file response below.
      const missingBuildAsset = isNextStaticPath(pathname, basePath, assetPathPrefix);

      // Strip internal headers from inbound requests so they cannot be
      // forged to influence routing or impersonate internal state.
      // Request.headers is immutable in Workers, so build a clean copy.
      {
        const filteredHeaders = filterInternalHeaders(request.headers);
        request = cloneRequestWithHeaders(request, filteredHeaders);
      }

      // ── 1. Strip basePath ─────────────────────────────────────────
      // Track basePath presence on the original request so the matcher
      // gating below can distinguish requests inside basePath (default
      // rules apply) from requests outside it (only opt-out rules apply).
      const hadBasePath = !basePath || hasBasePath(pathname, basePath);
      {
        const stripped = stripBasePath(pathname, basePath);
        if (stripped !== pathname) {
          const strippedUrl = new URL(request.url);
          strippedUrl.pathname = stripped;
          request = cloneRequestWithUrl(request, strippedUrl.toString());
          pathname = stripped;
        }
      }

      const dataNorm = normalizeDataRequest(request);
      if (dataNorm.notFoundResponse) return dataNorm.notFoundResponse;
      const isDataReq = dataNorm.isDataReq;
      if (isDataReq) {
        request = dataNorm.request;
        pathname = dataNorm.normalizedPathname;
      }

      // ── Image optimization via Cloudflare Images binding ──────────
      // Checked after basePath stripping so /<basePath>/_next/image works.
      if (isImageOptimizationPath(pathname)) {
        const allowedWidths = [
          ...(vinextConfig?.images?.deviceSizes ?? DEFAULT_DEVICE_SIZES),
          ...(vinextConfig?.images?.imageSizes ?? DEFAULT_IMAGE_SIZES),
        ];
        return handleImageOptimization(request, {
          fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
          transformImage: async (body, { width, format, quality }) => {
            const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
            return result.response();
          },
        }, allowedWidths, imageConfig);
      }

      // Delegate the canonical 9-step Next.js pipeline to the shared owner.
      // The worker adapter is responsible for: open-redirect guard, _next/static
      // 404 short-circuit, header filtering, basePath stripping, and image
      // optimization. runPagesRequest receives a clean, basePath-stripped request.
      const deps: PagesPipelineDeps = {
        basePath,
        trailingSlash,
        i18nConfig,
        configRedirects,
        configRewrites,
        configHeaders,
        hadBasePath,
        isDataReq,
        isDataRequest: isDataReq,
        ctx,
        matchPageRoute: typeof matchPageRoute === "function" ? matchPageRoute : null,
        // Pass the original (pre-basePath-stripping) URL to middleware so that
        // request.nextUrl.basePath reflects whether the URL actually had the
        // basePath prefix. Matches Next.js behavior and the prod-server.ts
        // equivalent (shared via wrapMiddlewareWithBasePath).
        runMiddleware:
          typeof runMiddleware === "function"
            ? wrapMiddlewareWithBasePath(runMiddleware, basePath, hadBasePath)
            : null,
        renderPage: typeof renderPage === "function"
          ? (req, resolvedUrl, options, stagedHeaders) =>
              renderPage(req, resolvedUrl, null, ctx, stagedHeaders, options)
          : null,
        handleApi: typeof handleApiRoute === "function"
          ? (req, apiUrl) => handleApiRoute(req, apiUrl, ctx)
          : null,
        serveFilesystemRoute: async (requestPathname, _stagedHeaders, phase) => {
          return fetchWorkerFilesystemRoute(
            request,
            requestPathname,
            phase,
            (assetRequest) => env.ASSETS.fetch(assetRequest),
          );
        },
      };

      const result = await runPagesRequest(request, deps);
      if (result.type === "response") {
        return finalizeMissingStaticAssetResponse(result.response, missingBuildAsset);
      }
      // Should not reach here for prod/worker (all callbacks supplied).
      return missingBuildAsset
        ? notFoundStaticAssetResponse()
        : new Response("This page could not be found", { status: 404 });

    } catch (error) {
      console.error("[vinext] Worker error:", error);
      return new Response("Internal Server Error", { status: 500 });
    }
  },
};

